## Regression test: -rewrite must retarget GOT references when .got spans
## TWO pages. Before the fix, the function-wide sweep bailed out on
## multi-page .got ("BOLT-ERROR: N unretargetable __BOLT_got_zero
## reference(s)") whenever orphan loads could not be paired; the leftover
## check aborted the rewrite. 450 preemptible globals (imported from a stub
## shared library) force a two-page .got; the loads live in a loop body
## laid out before both ADRPs (conditional entry + back-edge), so the
## forward pairing scan cannot reach them and the sweep must handle both
## pages.
##
## The repetitive inputs are generated by the RUN lines: the stub shared
## library (600 globals with known values) and the dispatch body (450 x25
## loads - var0-var159 through the x11 base, var160-var449 through x22 -
## plus the x23 var5 load feeding the loop check). The prologue and tail
## are extracted from between the markers below; the RUN lines themselves
## assemble as comments.

# REQUIRES: system-linux

# RUN: awk 'BEGIN { print ".data"; for (i = 0; i < 600; i++) printf ".globl var%d\n.p2align 3\nvar%d: .word %d\n", i, i, 256 + i }' > %t.stub.s
# RUN: %clang %cflags -shared -fPIC %t.stub.s -o %t.so
# RUN: sed -n '/^# PROLOG_BEGIN/,/^# PROLOG_END/p' %s | sed '1d;$d' > %t.s
# RUN: awk 'BEGIN { for (i = 0; i < 160; i++) printf "    ldr  x25, [x11, :got_lo12:var%d]\n", i; for (i = 160; i < 450; i++) printf "    ldr  x25, [x22, :got_lo12:var%d]\n", i; printf "    ldr  x23, [x11, :got_lo12:var5]\n" }' >> %t.s
# RUN: sed -n '/^# TAIL_BEGIN/,/^# TAIL_END/p' %s | sed '1d;$d' >> %t.s
# RUN: %clang %cflags -nostartfiles -e _start %t.s %t.so -o %t.orig -Wl,-q -fuse-ld=lld -Wl,-rpath,%t.dir
# RUN: llvm-bolt %t.orig -o %t.bolt -rewrite 2>&1 | FileCheck %s --check-prefix=CHECK-BOLT

## Structural checks (no execution): every GLOB_DAT slot is covered exactly
## once by a retargeted load whose displacement is congruent to the slot
## address modulo 0x1000 (the LO12 contract), and both ADRP base pages are
## pages of the output .got.
# RUN: bash -c 'l12() { while read h; do printf "%04x\n" $(( 0x$h % 0x1000 )); done; }; diff <(llvm-readelf -rW %t.bolt | awk "/GLOB_DAT/{print \$1}" | l12 | sort) <(llvm-objdump -d --no-show-raw-insn %t.bolt | grep -oE "ldr[[:space:]]+x25, \[x(11|22)(, #0x[0-9a-f]+)?\]" | sed -e "s/.*#0x\([0-9a-f]*\)\]/\1/" -e t -e "s/.*/0/" | l12 | sort) && echo "multipage static check: ok" | FileCheck %s --check-prefix=CHECK-STATIC'
# RUN: bash -c 'A=$(llvm-readelf -SW %t.bolt | awk "\$3==\".got\"{print \$5}"); Z=$(llvm-readelf -SW %t.bolt | awk "\$3==\".got\"{print \$7}"); P1=$(printf %x $(( 0x$A & ~0xfff ))); P2=$(printf %x $(( (0x$A + 0x$Z - 1) & ~0xfff ))); if llvm-objdump -d --no-show-raw-insn %t.bolt | grep -E "adrp[[:space:]]+x(11|22)" | grep -vE ", 0x($P1|$P2)\b"; then echo "adrp outside .got pages" >&2; exit 1; fi'

# CHECK-BOLT-NOT: BOLT-ERROR
# CHECK-STATIC: multipage static check: ok

# PROLOG_BEGIN
    .text
    .globl _start
    .p2align 2
_start:
    mov  w0, #0
    b    .Linit

.Lbody:
# PROLOG_END
# TAIL_BEGIN
    ldr  w24, [x23]
    cmp  w24, #0x105
    b.ne .Lfail
    add  w20, w20, #1
    cmp  w20, #2
    b.lt .Lbody
    ldr  x11, [x11, :got_lo12:var5]
    ldr  x24, [x11]
    cmp  w24, #0x105
    b.ne .Lfail
    b    .Lexit

.Linit:
    adrp x11, :got:var0
    adrp x22, :got:var160
    mov  w20, wzr
    cbz  w0, .Lbody

.Lfail:
    mov  x0, #1
    b    .Ldone
.Lexit:
    mov  x0, #0
.Ldone:
    mov  x8, #93
    svc  #0
# TAIL_END
